trigger:
  - main

pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: malleri-deployment

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: 14.x
  - task: AzureStaticWebApp@0
    inputs:
      app_location: "/"
      output_location: "dist"
    env:
      azure_static_web_apps_api_token: $(malleri-token-dev)
